package com.mycompany.cs.grp8.sd1a;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.awt.FontFormatException;
import java.awt.event.ItemEvent;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.Arrays;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.LookAndFeel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.FontUIResource;
import res.fonts.FontManager;

public class SignupForm extends javax.swing.JFrame {

    MainFeatures pnlFeatures = new MainFeatures();

    /**
     * Creates new form SignupForm
     */
    public SignupForm() {
        UIManager.put("OptionPane.messageFont",
                new FontUIResource(new Font(loadFonts(0).getFontName(), Font.PLAIN, 16)));
        UIManager.put("OptionPane.buttonFont",
                new FontUIResource(new Font(loadFonts(0).getFontName(), Font.PLAIN, 16)));
        UIManager.put("OptionPane.errorIcon",
                new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/cs/grp8/res/images/Warning.png")));
        UIManager.put("OptionPane.messageForeground", defaultDarkBtnText);
        UIManager.put("OptionPane.buttonForeground", defaultDarkBtnText);
        initComponents();
    }

    // Variable to be used for establishing connection and performing database
    // actions
    Connection con;
    PreparedStatement insert;
    dbConnection obj = new dbConnection();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDark = new javax.swing.JToggleButton();
        picColorIcon1 = new javax.swing.JLabel();
        pnlSignupFields = new javax.swing.JPanel();
        cbShowHidePass2 = new javax.swing.JCheckBox();
        lblSignup = new javax.swing.JLabel();
        txtNum2 = new javax.swing.JTextField();
        txtCreatePass = new javax.swing.JPasswordField();
        lblNum1 = new javax.swing.JLabel();
        lblCreatePass = new javax.swing.JLabel();
        lblConfirmPass = new javax.swing.JLabel();
        txtConfirmPass = new javax.swing.JPasswordField();
        txtFirstName1 = new javax.swing.JTextField();
        lblFirstName1 = new javax.swing.JLabel();
        txtSurname1 = new javax.swing.JTextField();
        lblSurname1 = new javax.swing.JLabel();
        calBday1 = new com.toedter.calendar.JDateChooser();
        lblBday1 = new javax.swing.JLabel();
        txtNo1 = new javax.swing.JTextField();
        txtStrt1 = new javax.swing.JTextField();
        lblStrt1 = new javax.swing.JLabel();
        lblNo1 = new javax.swing.JLabel();
        txtBrgy1 = new javax.swing.JTextField();
        lblBrgy1 = new javax.swing.JLabel();
        txtCity1 = new javax.swing.JTextField();
        lblCity1 = new javax.swing.JLabel();
        txtZip1 = new javax.swing.JTextField();
        lblZip1 = new javax.swing.JLabel();
        txtProvince1 = new javax.swing.JTextField();
        lblProvince1 = new javax.swing.JLabel();
        btnSignup1 = new javax.swing.JButton();
        pnlFeatures.setVisible(true);
        picFeatures = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ShadiFinTech");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDark.setBackground(new java.awt.Color(242, 242, 242));
        btnDark.setIcon(
                new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/cs/grp8/res/images/moon-stars.png"))); // NOI18N
        btnDark.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "",
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(242, 242, 242))); // NOI18N
        btnDark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarkActionPerformed(evt);
            }
        });
        getContentPane().add(btnDark, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 40));

        picColorIcon1.setIcon(
                new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/cs/grp8/res/images/ColorLogo.png"))); // NOI18N
        getContentPane().add(picColorIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        pnlSignupFields.setBackground(new java.awt.Color(242, 242, 242));
        pnlSignupFields.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbShowHidePass2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbShowHidePass2ItemStateChanged(evt);
            }
        });
        pnlSignupFields.add(cbShowHidePass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));

        lblSignup.setFont(new Font(loadFonts(0).getFontName(), Font.BOLD, 55));
        lblSignup.setForeground(new java.awt.Color(16, 20, 20));
        lblSignup.setText("Create Account");
        pnlSignupFields.add(lblSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 400, 90));

        txtNum2.setBackground(new Color(0, 0, 0, 0));
        txtNum2.setFont(new Font(loadFonts(9).getFontName(), Font.TRUETYPE_FONT, 18));
        txtNum2.setForeground(new java.awt.Color(16, 20, 20));
        txtNum2.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, grayLightText));
        pnlSignupFields.add(txtNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 360, 30));

        txtCreatePass.setBackground(new Color(0, 0, 0, 0));
        txtCreatePass.setForeground(new java.awt.Color(16, 20, 20));
        txtCreatePass.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, grayLightText));
        txtCreatePass.setEchoChar('\u00b7');
        pnlSignupFields.add(txtCreatePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 170, 30));

        lblNum1.setFont(new Font(loadFonts(7).getFontName(), Font.PLAIN, 16));
        lblNum1.setForeground(grayLightText);
        lblNum1.setText("Account Number");
        pnlSignupFields.add(lblNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        lblCreatePass.setFont(new Font(loadFonts(7).getFontName(), Font.PLAIN, 16));
        lblCreatePass.setForeground(grayLightText);
        lblCreatePass.setText("Create Password");
        pnlSignupFields.add(lblCreatePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        lblConfirmPass.setFont(new Font(loadFonts(7).getFontName(), Font.PLAIN, 16));
        lblConfirmPass.setForeground(grayLightText);
        lblConfirmPass.setText("Confirm Password");
        pnlSignupFields.add(lblConfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        txtConfirmPass.setBackground(new Color(0, 0, 0, 0));
        txtConfirmPass.setForeground(new java.awt.Color(16, 20, 20));
        txtConfirmPass.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, grayLightText));
        txtConfirmPass.setEchoChar('\u00b7');
        pnlSignupFields.add(txtConfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 180, 30));

        txtFirstName1.setBackground(new Color(0, 0, 0, 0));
        txtFirstName1.setFont(new Font(loadFonts(9).getFontName(), Font.TRUETYPE_FONT, 18));
        txtFirstName1.setForeground(new java.awt.Color(16, 20, 20));
        txtFirstName1.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, grayLightText));
        pnlSignupFields.add(txtFirstName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 100, 30));

        lblFirstName1.setFont(new Font(loadFonts(7).getFontName(), Font.PLAIN, 16));
        lblFirstName1.setForeground(grayLightText);
        lblFirstName1.setText("First Name");
        pnlSignupFields.add(lblFirstName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        txtSurname1.setBackground(new Color(0, 0, 0, 0));
        txtSurname1.setFont(new Font(loadFonts(9).getFontName(), Font.TRUETYPE_FONT, 18));
        txtSurname1.setForeground(new java.awt.Color(16, 20, 20));
        txtSurname1.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, grayLightText));
        pnlSignupFields.add(txtSurname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 110, 30));

        lblSurname1.setFont(new Font(loadFonts(7).getFontName(), Font.PLAIN, 16));
        lblSurname1.setForeground(grayLightText);
        lblSurname1.setText("Surname");
        pnlSignupFields.add(lblSurname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, -1, -1));
        pnlSignupFields.add(calBday1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 130, 30));

        lblBday1.setFont(new Font(loadFonts(7).getFontName(), Font.PLAIN, 16));
        lblBday1.setForeground(grayLightText);
        lblBday1.setText("Birth Date");
        pnlSignupFields.add(lblBday1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, -1, -1));

        txtNo1.setBackground(new Color(0, 0, 0, 0));
        txtNo1.setFont(new Font(loadFonts(9).getFontName(), Font.TRUETYPE_FONT, 18));
        txtNo1.setForeground(new java.awt.Color(16, 20, 20));
        txtNo1.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, grayLightText));
        pnlSignupFields.add(txtNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 80, 30));

        txtStrt1.setBackground(new Color(0, 0, 0, 0));
        txtStrt1.setFont(new Font(loadFonts(9).getFontName(), Font.TRUETYPE_FONT, 18));
        txtStrt1.setForeground(new java.awt.Color(16, 20, 20));
        txtStrt1.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, grayLightText));
        pnlSignupFields.add(txtStrt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 270, 30));

        lblStrt1.setFont(new Font(loadFonts(7).getFontName(), Font.PLAIN, 16));
        lblStrt1.setForeground(grayLightText);
        lblStrt1.setText("Street/Village/Subdivision");
        pnlSignupFields.add(lblStrt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, -1, -1));

        lblNo1.setFont(new Font(loadFonts(7).getFontName(), Font.PLAIN, 16));
        lblNo1.setForeground(grayLightText);
        lblNo1.setText("Bldg. No.");
        pnlSignupFields.add(lblNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, -1, -1));

        txtBrgy1.setBackground(new Color(0, 0, 0, 0));
        txtBrgy1.setFont(new Font(loadFonts(9).getFontName(), Font.TRUETYPE_FONT, 18));
        txtBrgy1.setForeground(new java.awt.Color(16, 20, 20));
        txtBrgy1.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, grayLightText));
        pnlSignupFields.add(txtBrgy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 180, 30));

        lblBrgy1.setFont(new Font(loadFonts(7).getFontName(), Font.PLAIN, 16));
        lblBrgy1.setForeground(grayLightText);
        lblBrgy1.setText("Barangay");
        pnlSignupFields.add(lblBrgy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, -1, -1));

        txtCity1.setBackground(new Color(0, 0, 0, 0));
        txtCity1.setFont(new Font(loadFonts(9).getFontName(), Font.TRUETYPE_FONT, 18));
        txtCity1.setForeground(new java.awt.Color(16, 20, 20));
        txtCity1.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, grayLightText));
        pnlSignupFields.add(txtCity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 170, 30));

        lblCity1.setFont(new Font(loadFonts(7).getFontName(), Font.PLAIN, 16));
        lblCity1.setForeground(grayLightText);
        lblCity1.setText("City/Town");
        pnlSignupFields.add(lblCity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, -1, -1));

        txtZip1.setBackground(new Color(0, 0, 0, 0));
        txtZip1.setFont(new Font(loadFonts(9).getFontName(), Font.TRUETYPE_FONT, 18));
        txtZip1.setForeground(new java.awt.Color(16, 20, 20));
        txtZip1.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, grayLightText));
        pnlSignupFields.add(txtZip1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 560, 90, 30));

        lblZip1.setFont(new Font(loadFonts(7).getFontName(), Font.PLAIN, 16));
        lblZip1.setForeground(grayLightText);
        lblZip1.setText("Zip Code");
        pnlSignupFields.add(lblZip1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 590, -1, -1));

        txtProvince1.setBackground(new Color(0, 0, 0, 0));
        txtProvince1.setFont(new Font(loadFonts(9).getFontName(), Font.TRUETYPE_FONT, 18));
        txtProvince1.setForeground(new java.awt.Color(16, 20, 20));
        txtProvince1.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, grayLightText));
        pnlSignupFields.add(txtProvince1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, 260, 30));

        lblProvince1.setFont(new Font(loadFonts(7).getFontName(), Font.PLAIN, 16));
        lblProvince1.setForeground(grayLightText);
        lblProvince1.setText("Province");
        pnlSignupFields.add(lblProvince1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 590, -1, -1));

        btnSignup1.setBackground(defaultLightBtnCol);
        btnSignup1.setFont(new Font(loadFonts(9).getFontName(), Font.BOLD, 20));
        btnSignup1.setForeground(defaultLightBtnText);
        btnSignup1.setText("Sign Up");
        btnSignup1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSignup1MouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSignup1MouseExited(evt);
            }
        });
        btnSignup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignup1ActionPerformed(evt);
            }
        });
        pnlSignupFields.add(btnSignup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 630, 130, 40));

        getContentPane().add(pnlFeatures, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 540, 720));

        getContentPane().add(pnlSignupFields, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 720));

        picFeatures.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/images/FeaturesBG.png"))); // NOI18N
        getContentPane().add(picFeatures, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, -1));
        getContentPane().add(pnlFeatures, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 540, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignup1MouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnSignup1MouseExited
        btnSignup1.setBackground(hoverLightBtnCol);
    }// GEN-LAST:event_btnSignup1MouseExited

    private void btnSignup1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSignup1ActionPerformed
        String accNum = txtNum2.getText();

        if (darkEnabled) {
            UIManager.put("OptionPane.background", DarkBG);
        } else {
            UIManager.put("OptionPane.background", LightBG);
        }

        if (!isIntegerFormat(accNum)) {
            javax.swing.JOptionPane.showMessageDialog(null, "Enter a valid account number.", "Invalid Account Number",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        } else if (!txtCreatePass.getText().equals(txtConfirmPass.getText())) {
            javax.swing.JOptionPane.showMessageDialog(null, "Passwords do not match.", "Check Entered Password",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        } else if (accNum.isBlank()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Fill up all fields", "Missing Information",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        } else {
        }

        try {
            con = obj.getConnection(); // Establish database connection
            String accountNum = txtNum2.getText();
            String userPass = String.valueOf(txtConfirmPass.getPassword());
            String firstName = txtFirstName1.getText();
            String lastName = txtSurname1.getText();
            String birthDate = String.valueOf(calBday1.getDate());
            int bldgNo = Integer.parseInt(txtNo1.getText());
            String street = txtStrt1.getText();
            String baranggay = txtBrgy1.getText();
            String city = txtCity1.getText();
            String province = txtProvince1.getText();
            int zipCode = Integer.parseInt(txtZip1.getText());
            insert = con.prepareStatement(
                    "insert into tblaccount(accountNum,userPass,firstName,lastName,birthDate,bldgNo,street,baranggay,city,province,zipCode)values(?,?,?,?,?,?,?,?,?,?,?)");
            insert.setString(1, accountNum);
            insert.setString(2, userPass);
            insert.setString(3, firstName);
            insert.setString(4, lastName);
            insert.setString(5, birthDate);
            insert.setInt(6, bldgNo);
            insert.setString(7, street);
            insert.setString(8, baranggay);
            insert.setString(9, city);
            insert.setString(10, province);
            insert.setInt(11, zipCode);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Added!"); // For testing
            new HomeInterface(darkEnabled).setVisible(true);
        } catch (SQLException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage()); // Display a user-friendly error
                                                                                       // message
        } catch (FontFormatException | IOException ex) {
            Logger.getLogger(SignupForm.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            dbConnection.closeConnection(); // Terminate connection
        }
    }// GEN-LAST:event_btnSignup1ActionPerformed

    private void btnSignup1MouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnSignup1MouseEntered
        btnSignup1.setBackground(defaultLightBtnCol);
    }// GEN-LAST:event_btnSignup1MouseEntered

    private void cbShowHidePass2ItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_cbShowHidePass2ItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            txtCreatePass.setEchoChar((char) 0);
            txtCreatePass.setFont(new Font(loadFonts(9).getFontName(), Font.TRUETYPE_FONT, 18));
        } else {
            txtCreatePass.setEchoChar('\u00b7');
            txtCreatePass.setFont(new Font("Segoe UI", Font.BOLD, 12));
        }
    }// GEN-LAST:event_cbShowHidePass2ItemStateChanged

    private boolean isIntegerFormat(String text) {
        String integerFormat = "\\d{5}\\s\\d{5}\\s\\d{5}\\s\\d{5}\\s\\d{5}"; // accepts only the format that banks use
        // for accounts
        return text.matches(integerFormat);
    }

    private void btnDarkActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDarkActionPerformed
        if (!darkEnabled) {
            setToDark();
        } else {
            setToLight();
        }
    }// GEN-LAST:event_btnDarkActionPerformed

    private void setToDark() {
        try {
            this.getRootPane().putClientProperty("JRootPane.titleBarBackground", DarkBG);
            this.getRootPane().putClientProperty("JRootPane.titleBarForeground", defaultDarkText);

            btnDark.setBackground(DarkBG);
            btnDark.setIcon(new javax.swing.ImageIcon(
                    getClass().getResource("/com/mycompany/cs/grp8/res/images/moon-stars1.png")));
            picColorIcon1.setIcon(new javax.swing.ImageIcon(
                    getClass().getResource("/com/mycompany/cs/grp8/res/images/ColorLogo.png")));

            darkEnabled = true;
            UIManager.setLookAndFeel(new FlatDarkLaf());

            SwingUtilities.updateComponentTreeUI(pnlSignupFields);
            pnlSignupFields.setBackground(DarkBG);
            lblSignup.setForeground(defaultDarkText);
            txtNum2.setForeground(defaultDarkText);
            txtCreatePass.setForeground(defaultDarkText);
            txtConfirmPass.setForeground(defaultDarkText);

            txtFirstName1.setForeground(defaultDarkText);
            txtSurname1.setForeground(defaultDarkText);
            calBday1.setForeground(defaultDarkText);

            txtNo1.setForeground(defaultDarkText);
            txtStrt1.setForeground(defaultDarkText);
            txtBrgy1.setForeground(defaultDarkText);
            txtCity1.setForeground(defaultDarkText);
            txtProvince1.setForeground(defaultDarkText);
            txtZip1.setForeground(defaultDarkText);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setToLight() {
        try {
            this.getRootPane().putClientProperty("JRootPane.titleBarBackground", LightBG);
            this.getRootPane().putClientProperty("JRootPane.titleBarForeground", defaultLightText);

            btnDark.setBackground(LightBG);
            btnDark.setIcon(new javax.swing.ImageIcon(
                    getClass().getResource("/com/mycompany/cs/grp8/res/images/moon-stars.png")));
            picColorIcon1.setIcon(new javax.swing.ImageIcon(
                    getClass().getResource("/com/mycompany/cs/grp8/res/images/ColorLogo.png")));

            darkEnabled = false;
            UIManager.setLookAndFeel(new FlatLightLaf());

            SwingUtilities.updateComponentTreeUI(pnlSignupFields);
            pnlSignupFields.setBackground(LightBG);
            lblSignup.setForeground(defaultLightText);
            txtNum2.setForeground(defaultLightText);
            txtCreatePass.setForeground(defaultLightText);
            txtConfirmPass.setForeground(defaultLightText);

            txtFirstName1.setForeground(defaultLightText);
            txtSurname1.setForeground(defaultLightText);
            calBday1.setForeground(defaultLightText);

            txtNo1.setForeground(defaultLightText);
            txtStrt1.setForeground(defaultLightText);
            txtBrgy1.setForeground(defaultLightText);
            txtCity1.setForeground(defaultLightText);
            txtProvince1.setForeground(defaultLightText);
            txtZip1.setForeground(defaultLightText);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void run(LookAndFeel theme) {
        try {
            UIManager.setLookAndFeel(theme);
            UIManager.put("Button.arc", 999);
        } catch (UnsupportedLookAndFeelException e) {
            System.out.println(e);
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, e);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SignupForm().setVisible(true);
        });
    }

    private final Color defaultLightBtnCol = new Color(51, 57, 140);
    private final Color hoverLightBtnCol = new Color(29, 29, 124);
    private final Color defaultLightBtnText = new Color(242, 242, 242);
    private final Color hoverLightBtnText = new Color(242, 242, 242);
    private final Color hoverLightTextCol = new Color(51, 57, 140);
    private final Color LightBG = new Color(242, 242, 242);
    private final Color defaultLightText = new Color(16, 20, 20);
    private final Color grayLightText = new Color(129, 131, 131);

    private final Color defaultDarkBtnCol = new Color(242, 242, 242);
    private final Color hoverDarkBtnCol = new Color(224, 225, 225);
    private final Color defaultDarkBtnText = new Color(51, 57, 140);
    private final Color hoverDarkBtnText = new Color(242, 242, 242);
    private final Color hoverDarkTextCol = new Color(147, 150, 191);
    private final Color DarkBG = new Color(30, 31, 31);
    private final Color defaultDarkText = new Color(242, 242, 242);

    public boolean darkEnabled = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnDark;
    private javax.swing.JButton btnSignup1;
    private com.toedter.calendar.JDateChooser calBday1;
    private javax.swing.JCheckBox cbShowHidePass2;
    private javax.swing.JLabel lblBday1;
    private javax.swing.JLabel lblBrgy1;
    private javax.swing.JLabel lblCity1;
    private javax.swing.JLabel lblConfirmPass;
    private javax.swing.JLabel lblCreatePass;
    private javax.swing.JLabel lblFirstName1;
    private javax.swing.JLabel lblNo1;
    private javax.swing.JLabel lblNum1;
    private javax.swing.JLabel lblProvince1;
    private javax.swing.JLabel lblSignup;
    private javax.swing.JLabel lblStrt1;
    private javax.swing.JLabel lblSurname1;
    private javax.swing.JLabel lblZip1;
    private javax.swing.JLabel picColorIcon1;
    private javax.swing.JLabel picFeatures;
    private javax.swing.JPanel pnlSignupFields;
    private javax.swing.JTextField txtBrgy1;
    private javax.swing.JTextField txtCity1;
    private javax.swing.JPasswordField txtConfirmPass;
    private javax.swing.JPasswordField txtCreatePass;
    private javax.swing.JTextField txtFirstName1;
    private javax.swing.JTextField txtNo1;
    private javax.swing.JTextField txtNum2;
    private javax.swing.JTextField txtProvince1;
    private javax.swing.JTextField txtStrt1;
    private javax.swing.JTextField txtSurname1;
    private javax.swing.JTextField txtZip1;
    // End of variables declaration//GEN-END:variables

    private Font loadFonts(int i) {
        FontManager fontManager = new FontManager();

        // Set the desired font for lblTitle
        return fontManager.registerFonts(i);
    }
}
